import { Inter, Lato, Poppins } from "next/font/google";

import "./globals.css";

const inter = Poppins({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: '400'
});



export const metadata = {
  title: "QFS Ledger admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
